### ISSUE TITLE
Compilation broke in Ubuntu 21.10

### ISSUE THREAD

**Issue by Longestboi** [RSDKModding/RSDKv2-Decompilation#4]
It looks like compilation on Linux has been broken in the latest commit ad7ce78.

In main.cpp:
```
#if !RETRO_USE_ORIGINAL_CODE

#if RETRO_PLATFORM == RETRO_WIN
#include "Windows.h"
#endif
```

I think compilation fails because there is no default platform for Linux. "RETRO_PLATFORM" is set to "RETRO_WIN" by default, and this makes this piece of code use Windows headers on a non-Windows platform.

**Comment by MegAmi24** [comment]
Known issue, we're working on it

**Comment by MegAmi24** [comment]
Should be fixed now
